
name: Fibo Service CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

permissions: read-all

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  service-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fibo unittest
        run: |
          python --version
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt

          python -m pip install -e .
          echo "==========================================="
          python -m unittest discover --verbose -s tests

  docker-build-push:
    needs: service-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tgthomson/fiboservice:test
  
  docker-validate:
    needs: docker-build-push
    runs-on: ubuntu-latest
    services:
      fibo:
        image: tgthomson/fiboservice:test
        ports:
          - 8080:80
    steps:
      - name: Test service endpoint
        run: |
          ## test sleeping before connecting, 'cause the service is just starting...
          sleep 5
          docker container ls
          curl -v http://localhost:8080/fibo/9

  ci-validated:
    needs:
      - service-validate
      - docker-validate
    runs-on: ubuntu-latest
    steps:
      - name: success
        if: ${{ success() }}
        run: |
          echo "### Workflow succeeded!" >> $GITHUB_STEP_SUMMARY
