
name: Fibo Service CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

permissions: read-all

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  service-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fibo unittest
        run: |
          python --version
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt

          python -m pip install -e .
          echo "==========================================="
          python -m unittest discover --verbose -s tests

  docker-build-push:
    needs: service-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fiboservice:test
      
      # - name: Validate docker image
      #   run: |
      #     docker run -p 127.0.0.1:5031:443 --detach --name test_container test_image
      #     docker container ls | grep test_container

      # - name: Stop the container
      #   if: ${{ always() }}
      #   run: |
      #     docker container stop test_container
      #     docker container prune --force

  docker-validate:
    needs: docker-build-push
    runs-on: ubuntu:latest
    steps:
      - name: pass
        run: echo "pass"

  ci-validated:
    needs:
      - service-validate
      - docker-validate
    runs-on: ubuntu-latest
    steps:
      - name: success
        if: ${{ success() }}
        run: |
          echo "### Workflow succeeded!" >> $GITHUB_STEP_SUMMARY
